### ISSUE TITLE
(config bug, not veonim) terminal sometimes swallowing first char input 

### ISSUE THREAD

**Issue by davidpumpkins** [veonim/veonim#394]
the problem is that when switching windows and trying to type in the terminal, the first char is sometimes not registered

the reason this happens is because i have mapped via key-transforms `cmd:down -> cmd`, `cmd:up -> esc`
so when pressing `cmd + tab` to switch windows, an `esc` is sent to the terminal which causes the next key press to not input in terminal.

i wonder if we can double check what keys are being sent to neovim when hitting `cmd + tab`. my guess is that by the time the `tab` key registers, the os takes over and initiates window switching. at this point veonim no longer gets the `tab` key, so the key event handler only seems `cmd:down, cmd:up` thus sending `esc`.

not sure if the timing works, but maybe we can check on `cmd:up` if the veonim window still has focus, and only send escape if veonim is in focus.

**Comment by breja** [comment]
actually

before blur it sends `cmd + meta`
after focus it sends `cmd` (transformed to escape)

**Comment by breja** [comment]
actually it can do both. on app switch it appears that most times it sends both `cmd + meta` and `cmd`

on window switch it's `cmd + meta` and after focus `cmd`

**Comment by breja** [comment]
i tried using `iohook` to listen to global keyboard events. it was bad and it should feel bad.

- was able to see cmd+tab key events in electron, but...
- native lib, complex building
- freezes on startup (tried webworkers & different process) - freezes the entire computer, even if in another app. LOLWUT
- requires accessibility permissions in macos

in the end, even if this worked perfectly, listening to cmd+tab is kinda moot, because that's very specific. what if the user creates a `cmd+shift+9` command to activate app switcher. back to the same problem.

i don't think this can be solved without a dirty hack.

i think the only dirty hack is to check if there was an `esc` (via cmd-> esc mapping probably) code sent right before the window was blurred (within a short ms timeframe). then we send another key to clear the `esc` from terminal on app focus. (do we need to only do this in the terminal? or is neovim itself fine in vim mode?)

it's really unlikely that someone would send esc right before the app was switched. the only way i can think for this to happen is someone uses an automation program to send `esc -> app switch` programmatically. let's see if that ever comes up...

**Comment by breja** [comment]
kinda dirty hack but i figured it out
