### ISSUE TITLE
Question: how to properly change-dir?

### ISSUE THREAD

**Issue by bfulop** [veonim/veonim#458]
Hello,

So now it's at least two months that I'm using Veonim for all my dev work. I'm still 100% satisfied, works great, enjoying using it every day!
Now, there's only one cosmetic issue that I always wanted to ask.

Here's a screenshot of bottom status line:

<img width="600" alt="screen shot 2018-08-31 at 11 05 04" src="https://user-images.githubusercontent.com/1718128/44904024-50b53380-ad0e-11e8-935f-fe7e2dd8c551.png">

My workflow is:

1. start Veonim
2. do `:Veonim change-dir ~/Work`
3. step down to the dir I want to set as root/work in

The status line shows the complete path, starting from `~/`, while on your screenshots it's always just `Veonim`.

Am I doing it wrong and there's a better way to change dir?

(also the GIT branch name doesn't fit in the space, but that's less bothering)

**Comment by breja** [comment]
Glad to hear Veonim is working for you!

In regards to the statusline directory - how would you like it to work?

Currently the logic works like this:

- Get the value of `:pwd`
- Try to make it relative to the path specified in `g:vn_project_root`
- Otherwise make it relative to home dir
- Otherwise absolute full path

Thus you could set the `g:vn_project_root` variable in `init.vim` to a more localized path to make the value of `:pwd` shorter.

For example, my projects are organized as such:
```
~/projects/Veonim
~/projects/this-is-so-sad
~/projects/alexa-play
~/projects/despacito
```

And in my init.vim
```
let g:vn_project_root = '~/projects'
```

So in the statusline the current dir will be one of `"Veonim", "this-is-so-sad", "alexa-play", or "despacito"`

I'm not sure if this is the best way of doing it. I personally don't really like the approach of setting the `project_root` variable - it feels kinda clunky and certainly not self-discoverable. It would be nice if it just did The Right Thing™

Perhaps we should just grab the last directory from `:pwd` value.

So a `:pwd` path like
```
/Users/a/projects/cool-stuff/dank-memes
```

Would display as `dank-memes` in the statusline

If there are two paths with the same last directory, we can go up the directory tree until we find a non-common ancestor.

```
/Users/a/projects/frontend/dank-memes --> displays "frontend/dank-memes"
/Users/a/projects/backend/dank-memes --> displays "backend/dank-memes"
```

The git branch should fit properly once the current directory is shorter. Either way it should probably overflow gracefully as one line truncated with ellipses instead of expanding to multiple lines. I'll make an issue for that.

I'm open to any thoughts/comments/suggestions

**Comment by bfulop** [comment]
Oh, I didn't know about the `vn_project_root` variable, setting it up right now!

The behaviour you just described, ie display only the last unique parts of the file paths sounds perfect for me! This lets me know in which vim session I'm in, but can still work in these deep subdirectories.

So one vote for this solution! 👍 

(I wish I knew typescript and had some time, I would love if I could contribute on these issues... If I have some time in the fall, I'll take a TS course. You are using hyperapp, right?)

**Comment by breja** [comment]
Okay, sounds good. That should work well for my workflow as well. Opened #462 and #459 to track the statusline issues.

Yes, using hyperapp. It is perhaps simpler than React. If you're familiar with Javascript, Typescript is fairly straight-forward to pick up.

Always happy to accept contributions (even testing and feedback is appreciated). 😃

**Comment by bfulop** [comment]
Great thanks! (for opening the issues)

I do know hyperapp, it's my preferred "framework"! 

For now I'll just stick to doing to QA testing, I cannot do too much damage with that!

BTW, I just saw this comment on the hyperapp Slack channel today:

[Who's using Hyperapp](
https://hyperapp.slack.com/archives/C41ECC0V6/p1535724033000100)? This could give some visibility to your project, unless you want to wait of course.
