### ISSUE TITLE
CPU usage going up after 20 minutes, language server maybe?

### ISSUE THREAD

**Issue by bfulop** [veonim/veonim#476]
I noticed that after editing a JavaScript file, the CPU usage (of the `npm` process) goes up, and I have the feeling that it's related to the language server.

Is there a way I can investigate this? I'm launching Veonim via `npm run start:release`. Can I open a debug console or just start Veonim without the language server and see how the CPU usage goes?

**Comment by breja** [comment]
Yeah I'd like to get a better grasp on CPU/energy/memory usage and make sure that resources stay within acceptable limits. I work mostly on a laptop and want the battery to last as long as possible.

A few ideas to checkout (as you suggested):

- chrome devtools -> `:Veonim devtools` 
  - if you get any perf profiling data or interesting logs on the issue that would help
- disable extensions
  - you can disable extensions by commenting out relevant lines in init.vim starting with `VeonimExt`  and reloading. I believe extensions will print out to the console when they are starting, so that could be a way of knowing if they are active or not <img width="361" alt="screen shot 2018-09-06 at 16 31 28" src="https://user-images.githubusercontent.com/2581815/45183522-57521800-b1f2-11e8-8398-a49cfcc2d72c.png">
- observe veonim process tree
  - in addition to extensions, veonim runs nvim in a process tree. This is interesting because sometimes I see high cpu usage on veonim, but as I drill down the process tree, I realize the culprit is a process running under a nvim terminal process.
  - tree view in Activity Monitor on MacOS <img width="439" alt="screen shot 2018-09-06 at 16 11 27" src="https://user-images.githubusercontent.com/2581815/45182535-8d41cd00-b1ef-11e8-83e1-3fd1d7ac481f.png">

I need to "git gud" at resource monitoring. I wonder if there is an *easy* way to watch the veonim process tree and be made aware of any subprocesses that are high CPU usage over a longer period of time...

**Comment by bfulop** [comment]
Thanks again @breja for the detailed instructions! Will check these out to track down the cpu spike. 

I have just closed Veonim, been using it for three hours straight and the cpu use stayed very low. One of the things I appreciate with Veonim is how light and fast it feels! In general, 95% of the time CPU use is minimal, except of course these runaway processes happen. I just do ':mksession!', restart the app and everything is working fine again. 

It could be that I'm doing a typo, a Veonim command without realizing it, that starts the extra process. 

I have istats menu running, it should help catch when the cpu rise happens.

**Comment by bfulop** [comment]
Just want to illustrate, what I mean by "enjoying Veonim's snappiness":

I always used GUI apps for my work, BBEdit then TextMate then Sublime. Then Webstorm for a year. It basically does everything for you, intellisense, debugging, building, profiling, refactoring, FTP etc etc. But I couldn't stand its sluggishness, especially with big files, so after a year went back to Sublime.  
Then used VSCode for about a year (since the beta, loved the WallabyJS plugin), but again got tired of that couple of milliseconds of delay (editing, moving text) so went back again to Sublime and spent a month setting it up to work like VSCode. 
Then there was [this article](https://code.visualstudio.com/blogs/2018/03/23/text-buffer-reimplementation) March this year, so back to VSCode again. Then I discovered the Oni editor and Vim and I have nothing but great things to say about them. I'm a supporter of Oni, because they are really great people and like their vision.

Then I tried Veonim, and of all the editors, it certainly feels one of the lightest, and for me, a joy to work with every day! It just boots my work morale, when I experience zero drag from the editor and seeing that the CPU load hardly goes above 5% while using it.  I do notice those milliseconds and is so much less tiring to work with an editor where I don't see any lag. Hard to explain. It's just a lot more enjoyable work environment.

I'm not a software architect, but I would guess it's because the UI thread is well separated from everything else? So even if some components CPU use goes up (the topic of this issue) the UI and editor still remains fast and is not at all affected. 

So yes, congrats for this great piece of software, it's greatly appreciated! :)

**Comment by bfulop** [comment]
@breja, I like to use the "nightly builds" of Veonim. I pull from the master branch, do `npm i` then `npm run build` finally `npm run start:release`.  
This of course runs Veonim via npm. Thus in the activity monitor I don't have a Veonim process. Is there a way to build a runnable Mac application?

Second question: how do you get the expandable activity tree of Veonim as per your screenshot?

**Comment by bfulop** [comment]
I still can't get to reproduce this consistently, the above method doesn't always result in a CPU spike. I'll let you know if I find something that you can work with...

**Comment by breja** [comment]
Happy to hear about your experience "enjoying Veonim's snappiness". It's great to know there are others who are finding Veonim useful. 😃 

Like you, I had similar experiences bouncing back between text editors and full-blown IDEs. Discovering Vim and its approach to modal editing was love at first sight. However, Vim lacks many useful IDE features - and while it can be somewhat coerced into an IDE experience, I quickly got tired of the hackiness of it all (also I don't like the way Vim looks, but that's perhaps a superficial complaint). So that's where Veonim and its previous experiments started from.

You're right about the architecture. I'm very obsessed with application responsiveness and smooth/efficient user interactions. I try to keep the UI thread lightweight. Anything that is heavy or non-UI related gets pushed off to web workers or external processes (like extensions/language servers). Also, perceived performance is more important than actual performance. For example, streaming partial results while searches are in progress (file finder, grep, etc.). Although I do have to give credit to (n)vim and their developers since nvim does the heavy lifting for the text editing.

That being said, there is still quite a lot of performance tuning work remaining. Veonim feels good, but it *must go faster*, heh.

I am also fan of Oni and look forward to their progress - Oni is a very ambitious project!

**Comment by breja** [comment]
To get a full build of Veonim you can do:

```
npm run build
npm run package
```

The resulting binaries should be under the `dist` folder.

Tree view in Activity Monitor can be found under View -> All Processes, Hierarchically. I sort processes by Name otherwise I find stuff jumps around too much. 
<img width="298" alt="screen shot 2018-09-09 at 7 52 00 pm" src="https://user-images.githubusercontent.com/2581815/45271087-2bdd6080-b472-11e8-9aa4-e0b3b0481936.png">


Another alternative is using `htop` and filtering on `veonim`

**Comment by breja** [comment]
I also added the process history usage tracker. This will track how much time the CPU spent at each 10% bracket. The process explorer and history usage tracker are only active when the Process Explorer window is open.

There is also a JSON export option which has the raw data (including total elapsed tracking time). This can be useful to calculate stats/generate reports/etc. 

<img width="962" alt="screen shot 2018-09-11 at 08 28 53" src="https://user-images.githubusercontent.com/2581815/45360363-56780800-b59d-11e8-94fd-3d4ad5c2a8ab.png">

**Comment by bfulop** [comment]
Wow, that looks really cool! I will be checking this while working. 

> I would not be surprised if there are some rare scenarios that cause the language server to get stuck on an expensive operation, but the editor no longer needs its result. 

I did have some strange behaviour with the JavaScript LSP error reporter, it seems to me this where those CPU spikes are coming from. While the general UI is always very responsive, sometimes the language server commands popup can take a while to open. 

I'll keep en eye on the process explorer and let you know if I see something useful.

**Comment by bfulop** [comment]
I'm getting closer to finding the steps to reproduce this bug.

I'm pretty sure that it all starts by invoking the `:Veonim rename` command on a JavaScript variable. From that moment on, the error checking seems to be behind the editing and take up a lot of CPU.

<img width="934" alt="screen shot 2018-09-13 at 15 52 21" src="https://user-images.githubusercontent.com/1718128/45494893-5b41e500-b772-11e8-8905-79faaf6802a2.png">

I will continue to test this scenario. Should I export the history JSON then and share it with you?

**Comment by breja** [comment]
If you want to export the history, sure.

So as I understand - the cpu usage of the language server stays high indefinitely after the rename operation?

**Comment by bfulop** [comment]
I uploaded a video that shows the CPU use going up and the langserver slowing down after the `:Veonim rename` command. Once I rename my variable even writing a simple `if` statement makes the langserver work overtime.

I also added the JSON dump to the folder.

Don't know if it has any importance, the file is in the AMD module format, starting with
```javascript
define(['jquery'], function($) {
...
})
```

(Yes the code is some ugly spaghetti, that's the reality of the front-end dev...)

https://app.box.com/s/zhun9w8pnjxm1j64ui7fss94qd3w97pn

**Comment by bfulop** [comment]
hm.. one more thing: as soon as I run `:Veonim rename`, a new file is created in the buffer list. It has the same name as the original file, but is listed as `undefined/theoriginalfile.js`.

I cannot navigate into it via the Veonim jump to buffer command, only by `[b` (`:bprevious`). It's an empty buffer.

**Comment by breja** [comment]
Thanks for the video/json uploads. They will definitely be helpful in investigating the root cause.

I think it's interesting how the CPU of the Veonim process goes up shortly after the languager server spikes. It could be that the langserver is throwing errors and the Veonim process is logging them out.

I'll play around with things and see what I discover; will keep this issue updated.

**Comment by breja** [comment]
Just an update...

I tried a rename scenario on a `js` file inside the Veonim project. I found similar behavior where the CPU usage and memory would spike for some time. The rename operation was also very slow. Doing a rename operation in a TypeScript file was significantly faster than JS.

I turned on tracing on the language server and noticed that after calling `textDocument/rename` the server would send an overwhelming amount of `window/logMessage` events - an event for each file in `node_modules`. I'm not sure what is going on the server side, but on the Veonim side the high CPU usage is most likely attributed to ingesting and parsing the large volume of `logMessage` events. Just a guess, but the CPU/memory spike probably scales with the amount of files in node_modules.

Message example:
```
readFile **some node_modules/*.js file** requested by TypeScript but content not available
```

I tried the same rename scenario inside VSCode using the same TypeScript/JavaScript language server extension and noticed very similar behavior with high CPU usage and memory.

I'm not comfortable with the behavior of the sourcegraph language server. I'm not sure, but perhaps this behavior is due to sourcegraph's server design decisions of loading all files in memory versus reading from disk (what TSServer does). This design probably makes sense for their cloud service offerings, but perhaps does not offer the best performance for local filesystem workflows.

I have been curious about trying out an alternative language server for TS/JS - I think now is a particularly appropriate time for that. Next step involves wrapping https://github.com/theia-ide/typescript-language-server into a VSCode extension and giving it a go + see how it compares to the sourcegraph language server.

**Comment by breja** [comment]
See #484 regarding the extra buffers on rename. I don't think that issue is related to the language server issues, but who knows.

**Comment by bfulop** [comment]
Thanks for the detailed explanation, sorry that I can't add much extra information to it...
Also, I'm working with a low-end machine (2015 12" Macbook) and I guess it has more trouble in processing all the `logMessage` events, creating even more langserver related bugs as I continue editing the file.

I was just planning to do and send you a performance profiling with the devtools, but I guess it's not needed then?

I may raise this issue then on the sourcegraph repo as well!

**Comment by breja** [comment]
So I wrapped https://github.com/theia-ide/typescript-language-server in a vscode extension and spent a few brief minutes playing with it. First impressions: good stuff! Almost instant startup time, significantly faster on most actions, and resource management is much lower. 

I briefly tried the JS rename scenario described in this issue and it was much faster with little resource usage. I would guess the performance difference is due to the design approach of lightly wrapping TSServer. 🤷‍♂️ 

A few issues found: #487 & #486. These are due to Veonim's incomplete LSP support for markdown documentation. I will fix these issues and switch to this langserver full-time to fully vet out its capabilities and behaviors. If all goes well then I'll probably promote it to "verified/suggested" status.

If you're feeling brave and want to try out the alternative langserver:
```vim
VeonimExt 'veonim/ext-typescript-javascript'
```
Repo: https://github.com/veonim/ext-typescript-javascript

RE: perf profile - if you capture something, I'll take a look. Otherwise (if you want) you can try the alternate langserver and if it still feels clunky, then we can dive deeper in the profiles.

**Comment by bfulop** [comment]
Thanks, that sounds really promising!

I just added the new `ext-typescript-javascript` langserver to my `init.vim` (and removed the sigraph one). I had the confirmation that the plugin was successfully installed and do see the ⚡️flash icon in the statusline. Other than this, the language server commands don't seem to work for me (tried `:Veonim symbols`, `:Veonim definition` and `:Veonim rename`. This is in an old-school, vanilla JavaScript file.

Do I need to do something else to make it work?

**Comment by breja** [comment]
Hmm, that's curious... it should Just Work™

I'll have to try the alternative langserver on other machines and see if I have similar issues.

Quick check:
- I assume you've restarted Veonim? 
- Your current working directory is something other than the default home `~`?
- Does the server show up in the process explorer under the "cli.js" process tree?
![screen shot 2018-09-18 at 11 39 15 am](https://user-images.githubusercontent.com/2581815/45699245-a162c400-bb37-11e8-8e1d-08d199af2e6e.png)

You could try the latest master where I have added trace logging. Enabling the trace logging will show any langserver messages under `debug` log level.

To activate tracing an entry needs to be added to Veonim local storage:
- key: `veonim-trace-flags`
- value: `langserv`

(You're a dev so I assume you're familiar with this - but just for reference...)
```javascript
localStorage.setItem('veonim-trace-flags', 'langserv')
```
![screen shot 2018-09-18 at 11 31 44 am](https://user-images.githubusercontent.com/2581815/45698638-775cd200-bb36-11e8-9920-fa0a99e474b1.png)
![screen shot 2018-09-18 at 11 28 40 am](https://user-images.githubusercontent.com/2581815/45698646-7b88ef80-bb36-11e8-9f47-10f1435bb4cf.png)

If that worked, you should see a confirmation log in console
![screen shot 2018-09-18 at 11 34 21 am](https://user-images.githubusercontent.com/2581815/45698828-ed613900-bb36-11e8-95e3-6b8be369e47c.png)

And the langserver messages
![screen shot 2018-09-18 at 11 37 46 am](https://user-images.githubusercontent.com/2581815/45699047-61034600-bb37-11e8-83a0-4e9806bc41e6.png)

Unrelated to tracing, but you should always see "activating extension..." and "starting extension..." log messages
![screen shot 2018-09-18 at 11 36 03 am](https://user-images.githubusercontent.com/2581815/45698942-31543e00-bb37-11e8-9074-effd88e3b2c2.png)

**Comment by bfulop** [comment]
Thanks, will try that tomorrow (I'm in Paris time...).

I am working in my home dir `~`, but did `:Veonim change-dir` to a deep subdirectory. I'll check the other steps next time I'm at the computer!

**Comment by bfulop** [comment]
I added the langserv trace-flags to local storage but didn't get any extra logs in the console.log even in Verbose mode.

I do get error messages though, when trying for example to look up a definition of a function:

```log
/Users/bfulop/Work/Libs/veonim/node_modules/vscode-languageserver-protocol/node_modules/vscode-jsonrpc/lib/messages.js:46 Uncaught (in promise) Error: Request textDocument/definition failed with message: Error processing request. No Project.
Error: No Project.
    at Object.ThrowNoProject (/Users/bfulop/Work/Libs/veonim/node_modules/typescript/lib/tsserver.js:85896:23)
    at ProjectService.getDefaultProjectForFile (/Users/bfulop/Work/Libs/veonim/node_modules/typescript/lib/tsserver.js:89066:46)
    at IOSession.Session.getFileAndProjectWorker (/Users/bfulop/Work/Libs/veonim/node_modules/typescript/lib/tsserver.js:91420:87)
    at IOSession.Session.getFileAndProject (/Users/bfulop/Work/Libs/veonim/node_modules/typescript/lib/tsserver.js:91405:29)
    at IOSession.Session.getDefinition (/Users/bfulop/Work/Libs/veonim/node_modules/typescript/lib/tsserver.js:91063:31)
```
still in the stack trace but about 20 lines lower, I see this:

```log
at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onread (net.js:639:20)
    at new ResponseError (/Users/bfulop/Work/Libs/veonim/node_modules/vscode-languageserver-protocol/node_modules/vscode-jsonrpc/lib/messages.js:46:28)
    at handleResponse (/Users/bfulop/Work/Libs/veonim/node_modules/vscode-languageserver-protocol/node_modules/vscode-jsonrpc/lib/main.js:430:48)
    at processMessageQueue (/Users/bfulop/Work/Libs/veonim/node_modules/vscode-languageserver-protocol/node_modules/vscode-jsonrpc/lib/main.js:258:17)
    at Immediate._onImmediate (/Users/bfulop/Work/Libs/veonim/node_modules/vscode-languageserver-protocol/node_modules/vscode-jsonrpc/lib/main.js:242:13)
```

So it's related to directory structure (_"Error: No Project"_)?

**Comment by bfulop** [comment]
This is interesting: in the same project as above, there are some files where I do get the langserver features (symbols list, rename, etc) but not in all files. I'm trying to track down why...

**Comment by bfulop** [comment]
Maybe I'm stupid, but I have the impression it has to do with loading files from `Session.vim`. The same file that I open from a blank vim session has no issues with the langserver. If I restore a vim session the files in it are not picked by the langserver? This could (maybe, potentially, hopefully) explain why in some cases the (S)CSS completions don't work?

**Comment by bfulop** [comment]
And can also confirm that the original issue is resolved for me by switching to the `theia-ide` langserver! 🎉

Everything is instantaneous and no CPU spike at all observed! Cool, great work on this!

**Comment by breja** [comment]
Good to hear that the alternative langserver is working out. I fixed the two display issues, so we should be good on that front.

I think the scenario with "no project" when starting veonim from a vim session makes some sense. Extensions require a `BufEnter` autocmd with a matching filetype to start language servers. Furthermore, language servers have to be notified of a buffer being opened with a `BufEnter` or `BufAdd` autocmd. I'm guessing the required autocmds are not firing or not firing for all buffers on session restore.

I opened #488 to investigate the session scenario and other possible scenarios where veonim might not be sending the needed events.

LSP should work with vim sessions - I plan to have veonim auto-save sessions and provide a restore list on startup and maybe through a menu. Soon™

**Comment by bfulop** [comment]
Great, again impressive work on making the swapping the langservers look so easy! Thanks for the explanation on the autocmds. Each time I learn something new and maybe in a few years will be able to contribute more than just bug reports and encouragement! 

So I guess I can respectfully close this issue, as the _no project_ issue will continue it's short career in #488...

Yes, I just started using vim sessions a couple of weeks ago and now I can't imagine my mornings without jumping back to the chaos that was the day before! Certainly beats the "blank page" artists block.
