### ISSUE TITLE
watcher collecting incomplete words

### ISSUE THREAD

**Issue by breja** [veonim/veonim#521]
don't do this

<img width="244" alt="screen shot 2018-10-08 at 9 02 11 pm" src="https://user-images.githubusercontent.com/2581815/46641064-7cadab00-cb3d-11e8-9b34-43c10a3c1647.png">

**Comment by chemzqm** [comment]
I don't emit content change event each time on `nvim_buf_lines_event`, since that event would fire quite a lot at same time when using snippet or action like undo and redo.
I use a debounce function to fire content change with content change calculated by using fast-diff.
https://github.com/neoclide/coc.nvim/blob/master/src/model/document.ts

**Comment by breja** [comment]
I decided to go back to the old way of doing things: not collecting completion words until leaving insert mode. After leaving insert mode the harvester will diff patch all change events and then collect any new keywords.

Hopefully that should resolve this issue.
