### ISSUE TITLE
npm, node commands not found

### ISSUE THREAD

**Issue by bfulop** [veonim/veonim#532]
This is a very beginner question and not really a bug in Veonim, but I just can't figure out how to run for example Prettier from Veonim.

It all starts with a clean install of Mojave then following [these steps](
https://github.com/creationix/nvm#git-install) to install Node via nvm.

In addition to the `~/.bashrc` and `~/.profile` files, I also added the lines to `~/.bash_profile`.

I installed vim-prettier and it does work if I run it from a _Neovim_ instance that I launched from a Terminal (in bash).   

If I try to run it from _Veonim_, I get the following error :

```
/bin/bash: prettier: command not found
```

I just tried the most simple method of running Prettier from the [Prettier Vim Setup page](
https://prettier.io/docs/en/vim.html#running-manually):

```
nnoremap gp :silent %!prettier --stdin --stdin-filepath % --trailing-comma all --single-quote<CR>
``` 

Would you have any guess as to why I cannot run the `prettier` command from inside Veonim? Is there a global `.bashrc` file that I should edit?

By the way this command also fails (_npm: command not found_ or something similar) when trying to [install vim-prettier](
https://github.com/prettier/vim-prettier#install) from inside Veonim:

```
" post install (yarn install | npm install)
Plug 'prettier/vim-prettier', { 'do': 'npm install' }
```

Sorry again for this extremely nooooob question!

**Comment by breja** [comment]
Are you using vim-plug? Veonim's built-in `Plug` command does not have any options like `{ 'do': 'cmds' }`. That's not document anywhere, so that's my bad, sorry. Perhaps I'll consider adding that functionality - it seems useful.

How do you have prettier installed? Globally or via the `do: npm i` config? Did you set any prettier config in a sourced bash file?

I think there's a bug here with Veonim not inheriting env vars in nvim properly. When Veonim starts the `nvim` process it passes along all the env vars. If I open a terminal and `echo $SOMEVAR` it prints out the var. But if I do the same inside nvim `:echo $SOMEVAR` I get nothing.

I'll have to investigate the best way to fix this. I could add all the env vars to the startup vimscript, but that feels a bit wrong. Hmm...

**Comment by breja** [comment]
Oke doke, the missing env vars should now be fixed in c270e14

Good observation - thanks for the report!

By the way, have you noticed any issues with Veonim on Mojave? I noticed a few annoyances since upgrading to Mojave (weird electron glitches, freezing on app startup, etc.). I think I'm going to try a clean install and see how that goes.

**Comment by bfulop** [comment]
Thanks, that's great news! 

I have a little trouble building Veonim with npm since updating, so I have to first fix that before getting back to business!

**Comment by bfulop** [comment]
I was playing around with GonVim and noticed the same issue. The `$PATH` elements reported by gonvim or Veonim is not the same as I get in the terminal or iTerm.

Finally, the only thing that solved it for me was adding this line in my `init.vim` 🤷‍♂️ : 

```
let $PATH .= ':/Users/bfulop/.nvm/versions/node/v10.12.0/bin'
```

Also tried [this tip](https://vi.stackexchange.com/questions/16019/neovim-terminal-not-reading-bash-profile) from stackexchange (setting the shell variable in `init.vim`) but it did not work either.

**Comment by breja** [comment]
Hmm, I'm not sure exactly what nvm is doing with the $PATH. I had a quick glance at the setup and it looks like they have it setup so a bash entry point like `bash_profile` will source the `nvm.sh` script. The `nvm.sh` script then seems to modify the $PATH further.

So I tried a similar flow and was able to see the correct $PATH.

I added the following lines to `.bash_profile`:
```bash
PATH="$PATH:$HOME/proj"
[ -s "$HOME/.blarg" ] && \. "$HOME/.blarg"
```

`~/.blarg` looks like:
```bash
PATH="$PATH:$HOME/proj/memes"
```

And the new path additions do show up in both Veonim and terminal:
<img width="465" alt="screen shot 2018-11-06 at 09 24 04" src="https://user-images.githubusercontent.com/2581815/48070619-48fa8b00-e1a6-11e8-8b4a-2d4847c34f9e.png">

I'll have to setup nvm and see what happens. Maybe there is something I'm missing.
