### ISSUE TITLE
the software is deleting files under nvim/pack on launch

### ISSUE THREAD

**Issue by slmjkdbtl** [veonim/veonim#535]
I'm on macos running veonim 0.11.0. 

I have 2 plugin directories `nvim/pack/extern` and `nvim/pack/local`, launching the app makes the whole `nvim/pack/local` disappear and half of `nvim/pack/extern` disappear. This has done serious damage to me cuz a lot of changes I made under `nvim/pack/local` haven't been pushed yet..

**Comment by breja** [comment]
Damn, really sorry about that! I pushed a temporary fix to no longer remove plugins from `nvim/pack` in `0.12.0`

Veonim needs a way to remove plugins no longer defined in `init.vim` (otherwise nvim will still load them) - obviously clearing out the entire `nvim/pack` directory is just stupid. I think a proper fix would be for Veonim to only remove plugins that Veonim itself downloaded previously.

**Comment by slmjkdbtl** [comment]
@breja Thanks for the quick fix!

**Comment by breja** [comment]
This was fixed back in November, but now we have the actual fix on master. Closing now.
