### ISSUE TITLE
Featured on Neovim related projects page!

### ISSUE THREAD

**Issue by bfulop** [veonim/veonim#540]
Hi,

I just saw that Veonim was added to the [list of Neovim GUIs](https://github.com/neovim/neovim/wiki/Related-projects/72b5af3ec08159552741ce848462e6a95d1f6db1) yesterday! 🎉

(Was wondering about the sudden increase of new stars on the project)

That's all, keep up the excellent work!

(sorry for raising an issue for this, just wanted to share the excitement... feel free to close it)

**Comment by breja** [comment]
Oh yeah, I was wondering where all the stars were coming from - especially since I haven't told anyone about this project yet. I'm actually not even sure how you found Veonim.

This is pretty cool though! Good to know the project appears interesting to others.

Thanks for sharing in the excitement and thanks for being an early alpha tester! 😄

**Comment by bfulop** [comment]
The pleasure is mine ! 😄

I heard about Veonim from the Onivim Discord channel where they were discussing canvas vs WebGL rendering. Some of the people who starred and followed Veonim also contribute to Onivim (bryphe, Akin, Loïc, Ryan C – very nice people). 

I also just noticed [chemzqm's comment](
https://github.com/veonim/veonim/issues/520#issuecomment-436454910). This week-end I was playing around with different Vim setups and language servers, one of which is the [Coc](https://github.com/neoclide/coc.nvim) plugin. chemzqm is the author of this repo (Coc). 

It's cool to see the Neovim community supporting each other!
