### ISSUE TITLE
Autocomplete box closes without allowing to select item

### ISSUE THREAD

**Issue by josemarluedke** [veonim/veonim#547]
Sometimes, the autocomplete box closes without allow to select any item.

It is not always predictable, sometimes it works, sometimes it just closes right after opening it.

Below is a gif showing that. Note that the problem happens half way through to the end.

![screen recording 2018-11-21 at 07 27 pm](https://user-images.githubusercontent.com/230476/48880252-752c2380-edc4-11e8-90d4-c39a9b1fa470.gif)

Here is my vimfiles: https://github.com/josemarluedke/vimfiles

**Comment by breja** [comment]
Hi, thanks for the issue.

I am not able to recreate the problem. It is obviously an issue that should be fixed. I will have to setup some test cases to play around with different timings to recreate the problem. 

My guess is the cause of the issue is async in nature. If a long-running completion request returns after the cursor has moved, and the completion items are no longer relevant for the new cursor position, the completion request should be cancelled. 

I will double check this to make sure completions requests are correctly cancelled.

**Comment by breja** [comment]
The implementation is wrong, it will be completely rewritten (when TBD)
