### ISSUE TITLE
VS code configuration

### ISSUE THREAD

**Issue by josemarluedke** [veonim/veonim#550]
How to pass a configuration to a vs code extension? I'm looking at adding [VS Code go](https://marketplace.visualstudio.com/items?itemName=ms-vscode.Go) for language service, but it needs to be enabled with a configuration.

Any guidance for that? 

Thanks.

**Comment by breja** [comment]
This is currently not possible, but something that I'm working on. I assume you are trying to pass config to the Go extension to use the language server instead?

For the immediate need, I made an extension that uses the same Sourcegraph Go language server: https://github.com/veonim/ext-go. I have verified this works with Veonim [0.13.2](https://github.com/veonim/ext-go).

init.vim config:
```
VeonimExt 'veonim/ext-go'
```

I'm not very familiar with Go, so I'd appreciate any feedback if the extension and language server is working as intended.

Thanks

**Comment by dhollinger** [comment]
So, if a VScode langserver extension requires configuration, it won't work yet?

**Comment by breja** [comment]
Correct - it does not work yet.

**Comment by christiaan-janssen** [comment]
Is there any update on this? I have a few extensions that I would like to use that require configuration.

**Comment by breja** [comment]
Yes this is now possible as of 0.22.0 with `g:vscode_config` variable. Example here: https://github.com/veonim/veonim/blob/master/docs/readme.md#configure-vscode-extensions

**Comment by breja** [comment]
VSCode configuration is now possible as of 0.22.0. There is still work to make sure all language extensions are loading correctly and can be configured properly.

It's been a while since this issue has been active. I'm going through cleaning the issue backlog and closing resolved and/or inactive issues. Please reopen if you still have questions or just want to post some funny memes.
