### ISSUE TITLE
Mouse pointer disappears

### ISSUE THREAD

**Issue by wookayin** [veonim/veonim#553]
Using 0.13.2 on macOS.
Mouse pointer disappears when it hovers the app.

![Mouse pointer disappears](https://user-images.githubusercontent.com/1009873/49891186-e6835300-fe13-11e8-8c39-23ac7edd6d1e.gif)

**Comment by Matrix89** [comment]
yep for some odd reason the cursor is set to none, it's really distracting

**Comment by breja** [comment]
Yeah, this falls in the category of "intentional" but terrible UX. I wanted this functionality since the cursor was distracting in full screen mode, and since there is no mouse support anywhere, it made sense at the time.

I will disable cursor hiding by default and maybe allow the option of hiding it behind some flag.

**Comment by breja** [comment]
@Matrix89 that's actually a great idea - I'll see if I can do that instead. Thanks for the suggestion!

**Comment by breja** [comment]
Closing since the original issue is fixed. I opened #578 to track hiding cursor in fullscreen after a timeout.
