### ISSUE TITLE
Support for parsing tags file

### ISSUE THREAD

**Issue by Mariappan** [veonim/veonim#555]
Thanks for creating this wonderful GUI
Its smooth, never thought electron app will be this much smoother.

Currently the GUI uses LSP to generate symbols and all.
Is it possible to add support for parsing ctags files and search symbols from it ?

Also searching for a word shows results based on files and we need to press two keys <C-N> <C-J> to move between entire results. Will it be possible to make the search result linear so that <C-J> traverse through all the search results continuously? This could be configuration driven also to let people decode their taste.

**Comment by breja** [comment]
I think we can make c-j/k traverse through file group search results. I also find it kind of annoying to have to jump between two keybindings to traverse the results. In a normal workflow I happen to want to traverse thru the entire list more often than cycling back thru the same file results (current behavior).

I haven't really used tags much so I could use some help in understanding their benefits. What advantages do tags have over a language server provided symbols? I could see their usefulness if a language does not have a language server (e.g. I don't think there is one for vimscript).

Is it possible to use one program to generate tags for multiple languages, or do we need a tags generator for each language?

**Comment by Mariappan** [comment]
Yes Making C-j,C-k to navigate through file group search results makes sense.

I primarily use C for development. There are some language servers available for C like cquery, ccls etc. But setting up it in new environment is difficult than setting up tags.

Ctags is the program which we normally use to generate tags for C,C++. Ctags supports multiple languages too.
http://ctags.sourceforge.net/
http://ctags.sourceforge.net/languages.html

Default vim supports tag navigation using Ctrl+t, Ctrl+] key combinations.
http://vim.wikia.com/wiki/Browsing_programs_with_tags

https://andrew.stwrt.ca/posts/vim-ctags/
This link has example of CtrlP plugin using tags file to navigate workspace symbols.

Since this has GUI, if we could parse tags files and list all symbols in like search results, it will be useful to navigate to workspace symbols.

**Comment by breja** [comment]
I will not be pursuing built-in tags support to Veonim at this time. I believe the language server approach is superior to tags. Veonim already supports the language server protocol which will work with any C/C++ language servers. The installation and configuration of language servers is still a pain, which is why I'm working hard on supporting the VSCode extension API. This should make the experience of setting up language support in Veonim similar or closer to VSCode.

After the vscode extension API is all ready and implemented, if support for C/C++ is still lackluster, I will look again at the possibility of supporting tags.

By the way, Veonim supports creating fuzzy user menus: https://github.com/veonim/veonim/tree/master/docs#create-your-own-fuzzy-menu

I think it should be possible to hook up some list of tags to the fuzzy menu and have it perform an action on selection of a menu item.
