### ISSUE TITLE
Still 0.2.x in Windows/Linux

### ISSUE THREAD

**Issue by Shougo** [veonim/veonim#558]
veonim uses below binary as internal neovim.

In macOS, it is upgraded to 0.3.2.
But in Windows/Linux is not updated yet.

Can you update it?

https://github.com/veonim/neovim

**Comment by breja** [comment]
Yes, I will update it. I have started the upgrade process - need to verify the builds are good.

**Comment by Shougo** [comment]
Thank you!
I will test it later.

**Comment by Shougo** [comment]
New binary package is not released yet...

**Comment by breja** [comment]
There were some issues with the newer binaries. I'm on holiday so I don't have access to linux/windows machines to test. Will work on this very soon

**Comment by Shougo** [comment]
OK.  Thanks.

**Comment by Shougo** [comment]
0.13.5 is already released.  I will try it later.

**Comment by breja** [comment]
Apologies for the long wait. The linux and windows builds have been upgraded to neovim 0.3.2 in [0.14.0](https://github.com/veonim/veonim/releases/tag/0.14.0). A few issues remain:

- `ext_messages` are not yet supported on linux and windows (see #556)
- windows build fails to download and install vim plugins and extensions (see #569)
(but you made your own plugin manager so that shouldn't be a problem 😉 )

Let me know how it goes and if you run into any other issues

**Comment by Shougo** [comment]
OK.  Thank you!
