### ISSUE TITLE
Remote attachment?

### ISSUE THREAD

**Issue by shaform** [veonim/veonim#562]
nvim-qt has an option to attach to existing nvim sessions: https://github.com/equalsraf/neovim-qt/wiki/Remote-attachment
gonvim also support this option: https://github.com/akiyosi/gonvim/pull/28

This enables us to use nvim-qt to attach to nvim running on remote servers via ssh, which is really useful. In this way, we are no longer being restricted to work on text-based terminals when connecting to remote servers.

I am wondering if veonim already supports this? I searched a little bit and find some issues about remote and client attach, but they doesn't seem to address this issue.

FYI, other similar issues from other neovim GUI projects: https://github.com/onivim/oni/issues/247, https://github.com/daa84/neovim-gtk/issues/21, https://github.com/rhysd/NyaoVim/issues/107, https://github.com/neovim/neovim/issues/5773.

**Comment by breja** [comment]
Veonim does not currently support remote connections. This is mainly because extensions and some veonim features need filesystem access. To make a useful remote veonim setup it would require the core of the program to run remotely on the server which greatly increases the complexity scope beyond nvim's `--listen` flag.

I did a POC a few weeks ago where I loaded Veonim's editor in a browser and communicated with nvim via WebSockets. I found localhost performance to be acceptable and that gave me the confidence to begin decoupling veonim's UI. Decoupling also means the possibility of exploring other UI frameworks in the future.

Now if we removed all extensions and veonim features out of the picture and used veonim purely as vanilla Neovim GUI, this would be significantly easier to solve. At that point though I'm not sure why you'd pay the Electron penalty when there are other native Neovim GUIs.

🍰 

![screen shot 2018-12-18 at 16 00 57](https://user-images.githubusercontent.com/2581815/50620710-11227200-0ecf-11e9-8003-e71ad5822640.png)

**Comment by breja** [comment]
The reason I don't like remote vim/nvim interfaces are because of increased input/render latency (assuming connections outside local networks). I mean remote is okay for occasional editing of remote server configs, but anything more than that is unpleasant.

My dream is to run neovim in the browser with WASM and bridge filesystem access to localhost, remote servers, or maybe even a virtual filesystem consisting of a git repo. Maybe one day.

**Comment by shaform** [comment]
Supposedly, if all the UI rendering is done locally, the basic features (e.g, externalized UI components) should be similarly fast as using TUI in ssh terminal, which is quite okay IMHO.

**Comment by ezh** [comment]
@breja There is a very simple case of permanent usage of remote nvim.

I have a linux server with 32Gb and 4xSSD raid and very heavy development process - hundred of thousand of files, zoo of languages and so on.
And I have a windows roadwarrior notebook with only 8Gb. It is really convenient to connect to remote machine and have everything like introspection, autocomplete, regex grep over huge collections with source code.

In this case local nvim on windows notebook is ALWAYS slower than remote connection, even with network latency. Memory and storage are cheap, so I guess there are a lot of people like me.

**Comment by breja** [comment]
@ezh is your linux server remote or on local network?

I think if a remote server is not too far geographically, the input latency could be around 20-30ms. It's definitely slower than a localhost setup but it might be usable. Considering a 60hz display that would be 2-3 frames more delay that local.

On a LAN this could work pretty well. It would be cool to run veonim server on a local server box and connect via local wifi with an ipad/tablet/chromebook (or any device which does not allow installing apps with filesystem access)

Another cool use case (which I kinda want) is being able to edit files remotely without having to install any app. If veonim had a web interface served over http/websockets it could connect via any web browser (assuming it was secured properly - maybe ssh tunnels)

I think the trade-offs between remote and higher input latency might be worth it. At least for MVP - I still think the final solution would be to WASM nvim but that's not a trivial problem to solve.

**Comment by ezh** [comment]
Most of the time I'm working from home. Server is on local network and ping less that 5ms. But I have ping not more 50ms (20-30) if I stay within the same city (not always, it depends). Some of our providers give link up to 100Mbit/s.

Actually 8Gb and windows is not enough to run all requirements. Workflow is terribly slow. And the bottleneck is not neovim itself, but tools that I use.

**Comment by shaform** [comment]
Looks like we now have a pretty good solution in VSCode: https://github.com/codercom/code-server. Though I haven't tried it yet.

**Comment by breja** [comment]
Just tried out code-server briefly - it seems pretty cool! Install the vim extension and it's even better. 😉 

I'm surprised Microsoft was not the first one to offer something like this. Or maybe the goal is for this startup to be bought out by Microsoft? It will be interesting to see how things develop.
