### ISSUE TITLE
Changing gui cursor color

### ISSUE THREAD

**Issue by appelgriebsch** [veonim/veonim#575]
I've installed the vim-ayu theme and set it to dark mode. Syntax highlighting and such are working properly, but the current cursor position is barely visible

<img width="953" alt="screenshot 2019-01-06 at 10 18 56" src="https://user-images.githubusercontent.com/6803419/50734242-b6259f00-119c-11e9-96ad-beda644f4e1d.png">

I've tried to update the `init.vim` file to set a gui cursor style, but it won't get recognised 

```vimrc
set guicursor=n:block-CursorNormal,i:hor10-CursorInsert,v:block-CursorVisual
hi! CursorNormal guibg=#E6B450
hi! CursorInsert guibg=#E6B450
hi! CursorVisual guibg=#E6B450
```

Any ideas?

**Comment by appelgriebsch** [comment]
Looks like I found a working solution:

1. install the vim plugin AfterColors by adding to init.vim: `Plug 'exvim/ex-aftercolors'`
2. create folder `~/.config/nvim/after/colors`
3. create file `common.vim` in the new folder with the cursor statements shown above

<img width="950" alt="screenshot 2019-01-06 at 17 08 22" src="https://user-images.githubusercontent.com/6803419/50738595-f6edda00-11d5-11e9-821f-8caa64aa6c94.png">

**Comment by breja** [comment]
Yeah I'm not sure why setting cursor highlight groups does not work in `init.vim`. I noticed that when I set the highlight groups in the colorscheme file, it works (colorscheme loaded after init.vim). Could probably use a VimEnter or WinEnter autocmd to set the cursor colors.

Perhaps I should add default guicursor highlight groups if they don't exist in a colorscheme file. I think many colorschemes forget or don't care about guicursor.

**Comment by nctubuddy** [comment]
However, setting `set guicursor=xxx` in colorscheme file `colors/xxx.vim` does not work either in veonim. We must manually run `colo xxx` again to make it take effect. (Probably because the default `colo xxx` command was also executed in `init.vim`. So it's impossible for colorschemes to care about guicursor. Providing a default `guicursor=...CursorNormal` setting would break most colorschemes since they don't have `CursorNormal`.
