### ISSUE TITLE
Use custom "nvim" binary?

### ISSUE THREAD

**Issue by bfredl** [veonim/veonim#588]
I tried this but the UI is empty apart from the statusbar. My first instinct would be try a different nvim binary but it is at least not documented how to do that. The only grep for `neovim-linux` is only in the `gen-api.js`, nothing for launching the app itself. Is there (could there be) a cmdline option to choose another nvim binary?

**Comment by breja** [comment]
Are you running from master? I think the packaged binaries should work on linux, but the code is very old. On master I have not yet built binaries for linux/windows that match the latest code. I probably need to decide if I will use neovim provided binaries or setup CI to build my own binaries from source.

As to your question about custom nvim path, I will probably not be supporting user provided nvim paths as I don't want to maintain backwards compatibility with older versions of neovim.

However, I do think it makes sense for developers to be able to use local nvim binaries. I modified the the `binaries.ts` module to contain the nvim path logic and optionally load from an env var `VEONIM_NVIM_PATH`:  https://github.com/veonim/veonim/blob/460c999504c8150652238bbd7590b8f2b7007715/src/support/binaries.ts#L21

The code will concat the specified path with `bin/nvim` and `share`

I'm open to ideas if there is a better way of doing this.

**Comment by bfredl** [comment]
@breja Yes, the idea is to test multigrid and stuff on master. I ran with nvim master, still no windows though (also if I disable config). Are veonim master supposed to work with nvim master, or are patches needed?

**Comment by breja** [comment]
veonim master works with https://github.com/veonim/neovim-source 

Unless there were breaking changes on neovim-master in the last 2 weeks, veonim should work with nvim master + `ext_messages` branch.

I think it might break if `ext_messages` is not present. veonim doesn't do feature detection since the included nvim binaries match the code and detection adds startup time to an already slow electron startup. I could probably add feature detection in development builds - might make testing custom nvim binaries easier instead of having to modify the flags in code.

Here are my steps for testing out veonim + nvim nightly on mac os:

```
$ cd $HOME
$ wget https://github.com/neovim/neovim/releases/download/nightly/nvim-macos.tar.gz
$ tar -zxf nvim-macos.tar.gz
$ ls
nvim-osx64
$ cd whatever-veonim-project-dir
```

set `ext_messages: false` in `master-control.ts`:
https://github.com/veonim/veonim/blob/2e60f31ec77448d9f11064902cc770474f5de967/src/core/master-control.ts#L32

```
$ VEONIM_NVIM_PATH=$HOME/nvim-osx64 node tools/start.js
```

My linux VM is having issues with webgl2, so I'm flying blind right now on linux support. I will need to install linux directly on hardware to test things out. Will report back once I get it working on linux.

**Comment by bfredl** [comment]
Rebased `ext_messages` on master, now it creates a window. The cursor moves when I insert text, but the text is invisible.

> I will need to install linux directly on hardware to test things out. 

Can't Xorg use software-only rendering, with mesa as gl implementation? I would expect Xorg to do that automatically if no hardware support can be detected.

**Comment by breja** [comment]
> Rebased `ext_messages` on master, now it creates a window. The cursor moves when I insert text, but the text is invisible.

Do you see any notable errors in the devtools console?

> Can't Xorg use software-only rendering...

Probably. I have 3D acceleration enabled (I guess that means GPU access?) and I can load webgl1 contexts. From my quick googling it seems like browser vendors blacklisted the vmware video drivers. It might be interesting to try parallels or virtualbox.

I think chromium has a flag to force software rendering, but it's not exposed in electron. If other users want veonim in a vm I could probably write a webgl2 shim. 🤷‍♂️

**Comment by breja** [comment]
I was wrong - I figured out how to turn off hardware acceleration. I can see the text rendering does not work. Do you see underlines like below? I'm not sure if that's the issue or just because of software rendering.

<img width="605" alt="screen shot 2019-01-22 at 20 10 52" src="https://user-images.githubusercontent.com/2581815/51575884-fca81880-1e81-11e9-84ad-5750992b7d4c.png">

**Comment by bfredl** [comment]
I actually got the weird underlines the first time it started, but together with an error message that it couldn't find syntax files. After fixing runtime location the underlines disappeared (but no next in either case). I will look into console output later.

**Comment by breja** [comment]
Okay well it's good that I can replicate the linux issues. I think the font glyph atlas is not being generated or loaded correctly in webgl. Will look into this asap.

**Comment by breja** [comment]
Master works on linux now

![screenshot from 2019-01-25 17-59-11](https://user-images.githubusercontent.com/2581815/51777432-14261200-20cb-11e9-9a47-04f3eac1c4ee.png)

I'm not exactly sure what was wrong, but I think it has something to do with the shader color texture atlas int/float calculation being different or the texture being loaded differently on mac vs linux. Maybe one day I'll figure it out.

**Comment by bfredl** [comment]
Works fine now, thanks!
