### ISSUE TITLE
Character under cursor has default font

### ISSUE THREAD

**Issue by khalidchawtany** [veonim/veonim#600]
Changing font or font size does not affect the character under the cursor.
![Screen Shot 2019-03-19 at 5 18 02 PM](https://user-images.githubusercontent.com/1681606/54612971-fb9efc00-4a6a-11e9-9c0f-d4310cf413a3.png)

**Comment by breja** [comment]
Sorry, fixed on master.

**Comment by tanyaionova** [comment]
Text under cursor is rendered higher than its line. Font is `Iosevka Term` patched with nerd font patcher.

![image](https://user-images.githubusercontent.com/42947087/55178963-8385b400-5197-11e9-9f99-9dfa29610af2.png)

**Comment by khalidchawtany** [comment]
I have the same issue.

**Comment by breja** [comment]
The cursor and cursor character are rendered in the DOM. This was done because it makes it super easy to control cursor shape. Of course this means the character rendering differs from the WebGL renderings.

I think there are a few ways to solve this:
- render the cursor & cursor character in WebGL (hard)
- do not use naive center align character position strategy - attempt to replicate shader position logic in JS
- maybe use canvas to render cursorchar? need to be careful to not introduce too many layers which have to be composited on every render pass

**Comment by breja** [comment]
The original issue is fixed. The misalignment also annoys me. It will be fixed, but first some bigger things need to happen.
