### ISSUE TITLE
Only one tab shown in the tab bar

### ISSUE THREAD

**Issue by khalidchawtany** [veonim/veonim#602]
When I add new tabs I expect a tab to be added to the tab bar

![veonim_tabs](https://user-images.githubusercontent.com/1681606/54613862-803e4a00-4a6c-11e9-8504-f739aeab8a8c.gif)

**Comment by breja** [comment]
Tabpage status is in the statusline
<img width="286" alt="Screen Shot 2019-03-19 at 20 03 13" src="https://user-images.githubusercontent.com/2581815/54649922-84756200-4a82-11e9-8169-3c2ffa037ebf.png">

Indeed, the tabpage names are missing. I don't think the names would fit in the statusline. Might need to create a new UI element to house the tabpages with names.

**Comment by khalidchawtany** [comment]
![Screen_Shot_2019-03-24_at_9_15_39_PM](https://user-images.githubusercontent.com/1681606/54883775-78224800-4e7a-11e9-873c-96be5bfc7b38.png)

**Comment by breja** [comment]
How would we display tabpages when we have multiple windows (splits)? For example, if I have 3 window splits like below and I create a new tabpage with `:tabnew`, where should we display the new tabpage title? 1, 2, or 3?
<img width="735" alt="Screen Shot 2019-03-24 at 15 34 29" src="https://user-images.githubusercontent.com/2581815/54884727-a720c580-4e4a-11e9-959a-093ff567475b.png">

The problem is that vim's tabpages are not analogous to what other editors call tabs. In Vim a tabpage can contain multiple windows (splits). It should probably have been called "workspaces" or something not so confusing.

Sorry if you were already aware of this. I'm open to ideas on improving the UI/UX.

**Comment by khalidchawtany** [comment]
We can have a small toolbar strip just under the window title. It should be thin and non-obstructive. On hover (Or on gt map) it could expand to reveal the tab names. It could slide to expand for eye candy :)

![collapsed](https://user-images.githubusercontent.com/1681606/54950321-146b4e00-4f52-11e9-8571-89c8330daf15.png)

![expanded](https://user-images.githubusercontent.com/1681606/54950332-19300200-4f52-11e9-8fc7-9f5c9bc734b2.png)

**Comment by breja** [comment]
Hmm, that's a pretty cool idea! When the tabpage bar is revealed by a keybind we could have each section have a key shortcut that when pressed switches to that tabpage.

Something like:
![54950332-19300200-4f52-11e9-8fc7-9f5c9bc734b2](https://user-images.githubusercontent.com/2581815/55037034-ce19fb80-4ff2-11e9-9ed4-14a8c4c0f70a.png)

**Comment by khalidchawtany** [comment]
> each section have a key shortcut that when pressed switches to that tab-page.

I really like your idea. This way, I can switch between mutable tabs with one key press. For example press `a` ooops wrong tab, press `s`. Switching tabs becomes so inexpensive that you would not want to read the tab names :)

**Comment by tjdevries** [comment]
Also was confused at first by the current behavior. Not 100% sure what the best solution is, but seeing the name of the current window in the tab would be helpful for remember what tab to switch back to (if possible).
