### ISSUE TITLE
Open via terminal

### ISSUE THREAD

**Issue by Mobilpadde** [veonim/veonim#616]
Silly, but I can't figure how to open `veonim` from terminal? Is it just me, or not working yet?

Oh, and I'm on manjaro linux, w/ deepin as vm.

**Comment by breja** [comment]
Are you looking for a global command that you can use to start veonim from a shell? Something like VSCode's `code script.sh`? If so that does not exist yet.

Or are you wondering how to open a file in the current vim window in a terminal inside veonim? That should be `vvim script.sh`

Or the veonim app binary does not launch?

**Comment by Mobilpadde** [comment]
I'm looking for the first one, could that please be implemented ASAP? I'd really love to use `veonim`, though without it, it's slowing me down :-1:

**Comment by justinmk** [comment]
> could that please be implemented ASAP?

@Mobilpadde this is rude.  Don't make  demands of other people's time.

**Comment by richin13** [comment]
@Mobilpadde can't you just symlink the `veonim` binary to a location under your `$PATH`

**Comment by Mobilpadde** [comment]
> > could that please be implemented ASAP?
> 
> @Mobilpadde this is rude. Don't make demands of other people's time.

Wasn't meant to be rude. I see, that I worded that one wrong. Meant if I'd get an estimate of the time frame. Again, I wasn't meaning to be rude :cry:

**Comment by Mobilpadde** [comment]
> @Mobilpadde can't you just symlink the `veonim` binary to a location under your `$PATH`?

Can't. I've tried, but getting errors when doing so :-1:

**Comment by richin13** [comment]
@Mobilpadde I added an [AUR](https://aur.archlinux.org/packages/veonim) package for veonim. Maybe you can give that a try, since you're using Manjaro.

Right now your problem is you have a recursive symlink:

- `/usr/bin/veonim` -symlinked-to-> `/bin/veonim`
- `/bin/veonim` -symlinked-to-> `/usr/bin/veonim`

If you don't want to use the AUR package you need to remove both symlinks and add a new one (either of both is fine) to point to the actual location of you `veonim` binary (wherever you extracted the downloaded build)

**Comment by Mobilpadde** [comment]
@richin13 trying it now! :+1:

**Comment by Mobilpadde** [comment]
@richin13 Nicely done! Works like a :gem:
