### ISSUE TITLE
couldn't input Chinese characters

### ISSUE THREAD

**Issue by Jiffies-Duke** [veonim/veonim#622]
it shows alphabet characters when I try to input Chinese. For example, if I type "ab" for Chinese "节" as what I do in notepad, the veonim screen shows "ab" instead of "节".

**Comment by breja** [comment]
How does it work in neovim/vim? Is it something handled by neovim or the terminal (when running neovim)?

**Comment by Jiffies-Duke** [comment]
I have installed the neovim. In both nvim and nvim-qt, it is ok to input Chinese characters. I also tested that in Oni , it is ok too. by the way, I am running this on a windows10.x64.zh-cn version.

**Comment by felixfong227** [comment]
![image](https://user-images.githubusercontent.com/13918481/55222074-e9307980-5245-11e9-940e-7bc314a6ab70.png)

What I am expecting is, both editor will show up "Hello 世界"

What actually happend is, both editor show up "Hello ??"

---

Confirm, I have the same issue regards of the Chinese characters not displaying properly

I usually span quite a lot of time just editing code with Chinese chatacters in it 🤔 

So this issue is also affecting me lot more then I originally thought it would be 

---

This is the part of my `init.vim` config

```init.vim
set termencoding=utf-8
set encoding=utf-8
set fileencoding=utf-8
```

**Comment by yesmeck** [comment]
The reason is veonim is not handling [CompositionEvent]() currently. 

For reference, [xterm.js](https://github.com/xtermjs/xterm.js) uses a hidden [textarea](https://github.com/xtermjs/xterm.js/blob/master/src/Terminal.ts#L685-L687) to handle the CompositionEvent.

**Comment by breja** [comment]
I believe the problem with text inputs is that they respect the system’s key repeat rate. On MacOS at least this requires some system config hacking that can get a little tricky. I know Oni had issues with this and I can’t remember if they ever fixed it.

Still, I think we can provide both options (window key events and text inputs) and let users configure the best option for themselves.

**Comment by yesmeck** [comment]
I don't think this issue is related to the system config.

In China, we use IME to input Chinese characters. IME is only enabled on `input`, `textarea` and `contenteditable` elements.

**Comment by yesmeck** [comment]
oni also uses a `input` to handle IME https://github.com/onivim/oni/blob/master/browser/src/Input/KeyboardInput.tsx#L66

**Comment by breja** [comment]
IME is not supported at this time. May revisit later when I have more free time.
