### ISSUE TITLE
[WebGL] Can not display CJK characters correctly

### ISSUE THREAD

**Issue by yesmeck** [veonim/veonim#639]
Giving the following file contains some Chinese characters:

```txt
// test.txt
测试
```

What it looks like on veonim:

<img width="712" alt="Screen Shot 2019-04-24 at 14 21 42" src="https://user-images.githubusercontent.com/465125/56636780-64961700-669c-11e9-9e33-94bd37c9f62c.png">

On neovim:

<img width="598" alt="Screen Shot 2019-04-24 at 14 23 05" src="https://user-images.githubusercontent.com/465125/56636812-81cae580-669c-11e9-9e0d-75295edcfe1d.png">

**Comment by breja** [comment]
I wonder if it has anything to do with font ligatures (as veonim does not support ligatures).

**Comment by benallan** [comment]
I can see the same problem on a mac with Japanese input support, it's almost like the wrong encoding is being used. I'm not sure, but I wouldn't have thought it's related to ligatures since these "double byte" characters display properly in editors without ligature support. 

Veonim on left, neovim on right:
<img width="1161" alt="Screen Shot 2019-08-03 at 11 13 07" src="https://user-images.githubusercontent.com/12690582/62406049-f4265c80-b5df-11e9-90f1-7c46f1d225bd.png">

When the cursor is over the character, it displays correctly:
<img width="1136" alt="Screen Shot 2019-08-03 at 11 13 54" src="https://user-images.githubusercontent.com/12690582/62406051-fc7e9780-b5df-11e9-8003-d4c09702b4b7.png">
