### ISSUE TITLE
How does it compare to Oni?

### ISSUE THREAD

**Issue by gunar** [veonim/veonim#640]
As you must know, [`Oni`](https://github.com/onivim/oni/) is also a GUI for `NeoVim`. I'm having trouble choosing between `Oni` and `veonim`. Could you please elaborate on what makes this project unique? Thanks in advance!

**Comment by breja** [comment]
I'm not sure if I'm the best person to answer this as my answer will have inherent bias.

However if you accept this bias, I'd say that the biggest differences are the goals driving Veonim vs Oni(2). My main goal with Veonim is to build an editor that I want to use for programming. I aim to build features that make my editing workflows as fast as possible. One important part of this is that Veonim aims to be very close to Neovim in terms of behavior and configuration. Switching between terminal Neovim and Veonim should not be a big deal. (Interestingly enough Veonim started out as terminal renderer).

The downside of this approach are inevitable legacy quirks and bugs that show up in what should be a modern GUI app. Trying to maintain vim compatibility can also take a long time to deliver new features that are consistent with the way vim works. For example, I've been working on debug adapter support for over a year now and it's difficult to design a good keyboard-only vim user experience versus just using a mouse.

Oni(2) on the other hand attempts to build a very nice modern editor that is approachable and familiar even to non-vim users. Oni(2) is probably the right choice for users who want to take advantage of the benefits of modal editing without the pain of setting up archaic workflows for simple things that  modern editors ship out of the box (like project find and replace - inb4 ur normie "unix as ide" memes) 

The downside of trying to build a modern editor is that some legacy baggage must be left behind. For example vimrc configuration is better for power users that like to tweak every knob and dial of their editors (at great pain, since vimrc is not easily discoverable) - meanwhile vscode configuration is probably a better choice for the large majority of users who just want to get shit done.

Oni(2) is certainly more polished and ready to use as a daily editor than Veonim is. Oni2 is a native app and as such the performance will be unmatched by any electron-based editors. I think Oni(2)'s progress is admirable and Bryphe and team have done a great job thus far. I frequently look up to their efforts for inspiration. It is certainly difficult to make money with open source so I hope the Oni2 endeavor will be successful.

Personally I think people should use whatever editor best suits their preferences. This is why I link to a number of other awesome GUIs on the readme page.

**Comment by Bubesh958** [comment]
@gunar so what did you choose oni or oni2 or veonim?

**Comment by breja** [comment]
I'm gonna close this out because it's not really an actionable item.

However for anyone who is stumbling upon this issue from the future, this is the state of things in May 2020:
- Oni is a dead meme
- Oni2 is getting close to a usable state. I tried it out and the typing latency is crazy fast. You should definitely check it out
- Veonim is a meme because of Electron and I hate Electron
