### ISSUE TITLE
Use FZF for file searching

### ISSUE THREAD

**Issue by ryanbas21** [veonim/veonim#641]
If there is a way, I would look into this if I had time, but fzf would help enable all fuzzy needs, and be super fast since ripgrep is already being used. (FD could be used for folder navigation or all of the searching).

I think this would help knockout the MRU requirement as there are ways to extend fzf yourself, including existing vim packages that have MRU with fzf.

**Comment by breja** [comment]
I've thought about integrating FZF but I'm not sure if it's a clear win just yet. Since FZF is not a library it means spawning a process, serializing data, streaming stdin data to the FZF process, streaming it back out to Node, and then parsing it back again. I'm not sure if this overhead is significant, but I imagine there are certainly cases where FZF will be faster.

Also I'm not sure if FZF supports searching across rich objects but I'm sure there's workarounds.

So to answer your question: FZF yeah maybe. Not a super high priority item (for me) right now unless there are significant performance problems that can be remedied by FZF.

**Comment by ryanbas21** [comment]
Gotcha. From a absolute performance standpoint it may not be a huge win, but could it be a win from the perspective of one tool to solve many problems?

File search, Folder search, Grep word, MRU, git fuzzy possibilities etc.

I can understand the effort to make it work and the gain not being enough value though

**Comment by breja** [comment]
I did some research to see if FZF could be integrated as a library. Fail: I couldn't figure out how to make it work.

Personally I like the matching/scoring that happens in [fuzz-aldrin-plus](https://github.com/jeancroy/fuzz-aldrin-plus). Another fuzzy library in the same spirit as FZF which I might poke at is [skim](https://github.com/lotabout/skim)
