### ISSUE TITLE
:bro[wse] o[ldfiles] just show unusable split window

### ISSUE THREAD

**Issue by kenardes** [veonim/veonim#648]
Hello guys, when i execute command :bro[wse] o[ldfiles][!] , instead of showing in full window with first list on top , it show a split window with last list like in picture below

![Screenshot_2019-07-28_06-17-21](https://user-images.githubusercontent.com/34209791/62000450-5e7f5e80-b101-11e9-8f49-3f4e65c62900.png)

btw, i use version 0.22.0 in arch linux

**Comment by breja** [comment]
This is just the way neovim sends the data. I will check latest master to see if it's still the same - if it is I will open an issue upstream.

**Comment by breja** [comment]
Closing because this can't be fixed in Veonim (well besides dirty hacks). Neovim would need to send more semantic information regarding the size of the incoming messages. Neovim does this already for message history `:messages` but not anything else as far as I know.

Either way even if this was fixable I would consider it out of scope/low priority since more modern solutions like fzf/coc.nvim will use floating windows to display various file/buffer navigation menus.
